# Generated by Django 5.2.8 on 2025-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
